language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install coverage nose-cov flake8 --use-mirrors"
  - "pip install -e . --use-mirrors"
  - "pip install python-coveralls"

before_script: "flake8"

script:  "nosetests"

after_success:
    - coveralls -c coverage.rc
